name: Workflow MAIN

# Executa apenas na branch MAIN
on:
  push:
    branches:
      - MAIN

jobs:
  main_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Run a one-line script
        run: |
          echo "Usando a Branch MAIN!"
          echo "EU AMO DEVOPS"
